.dashExpressComponents_js_metadata <- function() {
deps_metadata <- list(`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-graph.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-excel.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-graph.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-excel.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_express_components.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_express_components.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'plotly.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, async = 'eager'), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-plotlyjs.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, async = 'lazy'), class = "html_dependency"),
`dash_express_components` = structure(list(name = "dash_express_components",
version = "0.0.24", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-plotlyjs.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExpressComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
