name: Test

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: python -m pip install dash[dev,testing] flit invoke semver termcolor pandas scipy scikit-image dask kaleido
      - name: Build the components
        run: |
          npm run build
          python setup.py sdist
      - name: Test components
        run: |
          pytest --cov=./dash_express_components
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
