name: Test

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install software
        run: sudo apt-get install -y chromium-browser          
      - name: Install Python dependencies
        run: python -m pip install dash[dev,testing] flit invoke semver termcolor pandas scipy scikit-image dask kaleido pytest pytest-cov webdriver-manager numexpr shapely
      - uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &        
      - name: Build the components
        run: |
          npm run build
      - name: Upload generated files
        uses: actions/upload-artifact@v2
        with:
          name: dash-express-components
          path: dash_express_components
      - name: Test components
        run: |
          pytest --cov=dash_express_components
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
